/**
 * bake.mjs — §4.3. Real raster assets, made at build time.
 *
 * The four hero entities are signed distance fields raymarched in a
 * fragment shader (src/fx/entitySDF.js). Raymarching them while the player
 * is playing would be absurd — soft shadows and five-tap AO at 900×760 is
 * not something to do on a laptop mid-scene — so they are rendered once,
 * here, in headless Chromium, and written into src/generated/entityAssets.js
 * as PNG data URIs.
 *
 * That file is committed, so a clone builds without a GPU and the game
 * ships with genuine raster art rather than canvas primitives.
 *
 *   node tools/bake.mjs          bake and write
 *   node tools/bake.mjs --check  fail if the committed bake is stale
 */

import { chromium } from 'playwright';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createServer } from 'node:http';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'src/generated/entityAssets.js');
const CHECK = process.argv.includes('--check');
const TMP = join(ROOT, '.shot');
await mkdir(TMP, { recursive: true });

/* A page that imports the SDF module directly, so the bake does not depend
 * on the game booting. Three is vendored, so it is served from disk. */
const sdf = await readFile(join(ROOT, 'src/fx/entitySDF.js'), 'utf8');
const three = await readFile(join(ROOT, 'vendor/three/three.module.min.js'), 'utf8');
const threeCore = await readFile(join(ROOT, 'vendor/three/three.core.min.js'), 'utf8');

// three.module re-exports from three.core; keep the pair together.
await writeFile(join(TMP, 'three.core.min.js'), threeCore);
await writeFile(join(TMP, 'three.js'), three);
await writeFile(join(TMP, 'entitySDF.js'), sdf.replace(/from ['"]three['"]/, "from './three.js'"));
await writeFile(join(TMP, 'bake.html'), `<!doctype html>
<html><head><meta charset="utf-8"></head><body>
<script type="module">
import { renderEntity, KINDS } from './entitySDF.js';
window.__bake = async (scale) => {
  const out = {};
  for (const k of KINDS) {
    const c = renderEntity(k, scale);
    if (!c) { out[k] = null; continue; }
    out[k] = c.toDataURL('image/png');
  }
  return out;
};
window.__ready = true;
</script></body></html>`);

const server = createServer(async (req, res) => {
  const name = req.url === '/' ? '/bake.html' : req.url.split('?')[0];
  let buf;
  try { buf = await readFile(TMP + name); }
  catch { res.writeHead(404); res.end('no'); return; }
  res.writeHead(200, {
    'Content-Type': name.endsWith('.js')
      ? 'text/javascript; charset=utf-8' : 'text/html; charset=utf-8',
  });
  res.end(buf);
});
await new Promise(r => server.listen(0, r));

const browser = await chromium.launch({
  executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome',
  args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'],
});
const page = await browser.newPage({ viewport: { width: 400, height: 300 } });
page.on('pageerror', e => console.log('pageerror: ' + e.message));
await page.goto(`http://localhost:${server.address().port}/`, { waitUntil: 'load' });
await page.waitForFunction(() => window.__ready === true, null, { timeout: 40000 });

console.log('raymarching…');
const t0 = Date.now();
const assets = await page.evaluate(() => window.__bake(1));
console.log(`  ${((Date.now() - t0) / 1000).toFixed(1)}s`);

let missing = 0;
const lines = [];
for (const [k, uri] of Object.entries(assets)) {
  if (!uri || uri.length < 2000) {
    console.log(`  FAIL  ${k} — no render`);
    missing++;
    continue;
  }
  console.log(`  ok    ${k.padEnd(10)} ${(uri.length / 1024).toFixed(0)} KB`);
  lines.push(`  ${k}: '${uri}',`);
}

await browser.close();
server.close();

if (missing) {
  console.log(`\n${missing} entities did not render — not writing.`);
  process.exit(1);
}

const body = `/**
 * entityAssets.js — GENERATED BY tools/bake.mjs. Do not edit by hand.
 *
 * §4.3. The four hero entities, raymarched once at build time from the
 * signed distance fields in src/fx/entitySDF.js and inlined here as PNG
 * data URIs, so the shipped game does not raymarch anything while the
 * player is playing.
 *
 * Regenerate with \`node tools/bake.mjs\` after changing entitySDF.js.
 * Verify with \`node tools/bake.mjs --check\`.
 *
 * An empty object is valid — entityArt.js falls back to the 2D drawings —
 * but it is not what should be committed.
 */
export default {
${lines.join('\n')}
};
`;

const hash = (s) => createHash('sha1').update(s).digest('hex').slice(0, 12);

if (CHECK) {
  let cur = '';
  try { cur = await readFile(OUT, 'utf8'); } catch { /* not baked yet */ }
  if (hash(cur) === hash(body)) {
    console.log('\nthe committed bake is current.');
    process.exit(0);
  }
  console.log('\nthe committed bake is STALE — run: node tools/bake.mjs');
  process.exit(1);
}

await writeFile(OUT, body);
console.log(`\nwrote ${OUT} (${(body.length / 1024).toFixed(0)} KB)`);
